### ISSUE TITLE
ImportError: libcudart.so.9.2: cannot open shared object file: No such file or directory

### ISSUE THREAD

**Issue by sclzsx** [speedinghzl/CCNet#80]
I run the code branch CCNet-pytorch1.1, my environments are:
pytorch 1.4  torchvision 0.5.0
cuda 10.2
python 3.6
However, this error happend:
root@3178500507b3:/workspace/CODE/CCNet-pytorch-1.1# python3 train.py
Detected CUDA files, patching ldflags
Emitting ninja build file /workspace/CODE/CCNet-pytorch-1.1/cc_attention/build/build.ninja...
Building extension module rcca...
ninja: no work to do.
Loading extension module rcca...
Traceback (most recent call last):
  File "train.py", line 17, in <module>
    import networks
  File "/workspace/CODE/CCNet-pytorch-1.1/networks/__init__.py", line 3, in <module>
    import networks.ccnet
  File "/workspace/CODE/CCNet-pytorch-1.1/networks/ccnet.py", line 13, in <module>
    from cc_attention import CrissCrossAttention
  File "/workspace/CODE/CCNet-pytorch-1.1/cc_attention/__init__.py", line 1, in <module>
    from .functions import CrissCrossAttention, ca_weight, ca_map
  File "/workspace/CODE/CCNet-pytorch-1.1/cc_attention/functions.py", line 24, in <module>
    extra_cuda_cflags=["--expt-extended-lambda"])
  File "/usr/local/lib/python3.6/dist-packages/torch/utils/cpp_extension.py", line 680, in load
    is_python_module)
  File "/usr/local/lib/python3.6/dist-packages/torch/utils/cpp_extension.py", line 877, in _jit_compile
    return _import_module_from_library(name, build_directory, is_python_module)
  File "/usr/local/lib/python3.6/dist-packages/torch/utils/cpp_extension.py", line 1088, in _import_module_from_library
    return imp.load_module(module_name, file, path, description)
  File "/usr/lib/python3.6/imp.py", line 243, in load_module
    return load_dynamic(name, filename, file)
  File "/usr/lib/python3.6/imp.py", line 343, in load_dynamic
    return _load(spec)
ImportError: libcudart.so.9.2: cannot open shared object file: No such file or directory
 Could you help me what should I do?

**Comment by ygjwd12345** [comment]
I surface the same problem

**Comment by speedinghzl** [comment]
Please delete the dir [cc_attention/build](https://github.com/speedinghzl/CCNet/tree/pytorch-1.1/cc_attention/build). CC Attention module will compile using your local installed CUDA 10.2.

**Comment by shrutishrestha** [comment]
@ygjwd12345 how was this problem solved? I am having the same issue.
